### ISSUE TITLE
There should be a way to quickly recover an accidentally deleted task

### ISSUE THREAD

**Issue by RezaT4795** [MahStudio/Denna#101]
For example, Outlook app, or Messaging app. Whenever you delete a message, a thin red bar appears in the bottom of the page, saying "Deleted" and there's an undo button to bring it back.
It will stay there for a few seconds.
It would be very nice if the same thing happen in Denna, so if we accidentally deleted a task, we can bring it back.

**Comment by Mohsens22** [comment]
Denna hard deletes tasks one you click delete. So it's inaccessible after delete.
How ever in the next version I'll ask for a confirmation so nothing will be deleted accidentally.
Please close this issue once we rolled an update with a confirmation while delete.

**Comment by RezaT4795** [comment]
@Mohsens22 Ok
