### ISSUE TITLE
Explain what the timeline is when the user has no items there

### ISSUE THREAD

**Issue by colinkiama** [MahStudio/Denna#2]
Because currently, it's hard to even know what to do at that page if you've never used the app before.

Hiding the empty lists and showing telling the user how to make tasks/hobbies would create a way better first-time experience

**Comment by Mohsens22** [comment]
can you elaborate more?

**Comment by colinkiama** [comment]
> can you elaborate more?

On the timeline view, when the user has no task or hobbies created, explain to them how to create tasks, hobbies and how to interact with them. A little tutorial.


For example:

```
Press the '+' button to add a task, you can change the status of the task based on your progress with: (Three task statuses)


For recurring tasks, use the press the (Add Hobby Icon) to add a new hobby.


Remember that you can also set reminders and alarms for these too.
```


A message like that is a lot more useful then an empty list of tasks.

**Comment by Mohsens22** [comment]
I agree. Added to V2.0 milestone
