### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by XxKVAxX** [MahStudio/Denna#37]
Crash after login in app

**Comment by Mohsens22** [comment]
Please include the crash stack trace screenshot

**Comment by Mohsens22** [comment]
It's related to #7 .
![image](https://user-images.githubusercontent.com/22152065/43599307-6ccba62c-969c-11e8-881c-04e97e4e4acf.png)
![image](https://user-images.githubusercontent.com/22152065/43599327-77a5e382-969c-11e8-8e34-3e7062fdf884.png)
