### ISSUE TITLE
min height of window should be more 

### ISSUE THREAD

**Issue by alighamari** [MahStudio/Denna#48]
min height of window should be more and min width of window **can** be less (I don't mean it have to be less but it can be)
![image](https://user-images.githubusercontent.com/24440862/44156118-6181a65e-a0c4-11e8-8d9c-7f3a11a300f7.png)

**Comment by Mohsens22** [comment]
This is managed by windows. I'd better not change it.
I can make swipe panel a bit shorter, so we can save more space.
Also I can make other parts of app compatible with this size.
