### ISSUE TITLE
padding for "save and dismiss" button

### ISSUE THREAD

**Issue by alighamari** [MahStudio/Denna#49]
![image](https://user-images.githubusercontent.com/24440862/44156248-b7fa71d2-a0c4-11e8-83e8-24d0cefa507b.png)
save and dismiss button should have same (or more) padding with bottom than the padding with each other

**Comment by Mohsens22** [comment]
Fixed
![image](https://user-images.githubusercontent.com/22152065/44158249-841a8000-a0c9-11e8-8d30-89e414417a8f.png)
