### ISSUE TITLE
App need small UI changes

### ISSUE THREAD

**Issue by XxKVAxX** [MahStudio/Denna#59]
![wp_ss_20180821_0001](https://user-images.githubusercontent.com/40000756/44384992-c0fdd100-a526-11e8-823a-57b7f555c684.png)
![wp_ss_20180821_0002](https://user-images.githubusercontent.com/40000756/44384994-c0fdd100-a526-11e8-9484-b902cd40354c.png)

**Comment by Mohsens22** [comment]
What phone ?

**Comment by XxKVAxX** [comment]
@Mohsens22 640 DS LTE
