### ISSUE TITLE
Swipe panel

### ISSUE THREAD

**Issue by XxKVAxX** [MahStudio/Denna#60]
![wp_ss_20180821_0005](https://user-images.githubusercontent.com/40000756/44385256-8ba5b300-a527-11e8-94bc-600e7e07b34d.png)
![wp_ss_20180821_0006](https://user-images.githubusercontent.com/40000756/44385257-8ba5b300-a527-11e8-97b7-e5d2d1b2e5bb.png)
![wp_ss_20180821_0007](https://user-images.githubusercontent.com/40000756/44385259-8ba5b300-a527-11e8-9e44-81aa3fe6ca2a.png)
Problem with postpone

**Comment by Mohsens22** [comment]
Can you elaborate?
How can I reproduce this issue?

**Comment by Mohsens22** [comment]
fixed in #80
