### ISSUE TITLE
Can't upgrade from V1 builds on mobile.

### ISSUE THREAD

**Issue by rezacloner47** [MahStudio/Denna#63]
Tried to upgrade from V1 build (Store version) but failed. There's no error and it gets installed. But the app is the same version.

**Comment by Mohsens22** [comment]
@rezacloner47 Tet this again plz

**Comment by rezacloner47** [comment]
Still the same. At least on mobile.

**Comment by Mohsens22** [comment]
@rezacloner47 Try on PC

**Comment by Mohsens22** [comment]
![image](https://user-images.githubusercontent.com/22152065/44628875-8b5d4b80-a95d-11e8-8af6-f886304747ae.png)

**Comment by rmclassic** [comment]
@Mohsens22 https://stackoverflow.com/questions/38565695/error-0x800b0100-the-app-package-must-be-digitally-signed-for-signature-validat

**Comment by Mohsens22** [comment]
I moved back to version 1 release, associated with windows store and tried to update. It worked. 
But still can't upgrde from a V1 to V2
