### ISSUE TITLE
Data migration from V1 to V2, marks all the migrated tasks as "Done"

### ISSUE THREAD

**Issue by rezacloner47** [MahStudio/Denna#69]

**Comment by rezacloner47** [comment]
![untitled](https://user-images.githubusercontent.com/25543782/44390233-07acf480-a542-11e8-9639-289c2d273255.png)
V1


![untitled](https://user-images.githubusercontent.com/25543782/44390309-3aef8380-a542-11e8-8e5d-e1bff04d5f5a.png)
V2

**Comment by Mohsens22** [comment]
@rezacloner47 Do this:
Go to V1,
Make a task Done
Then Postpone another
Then move to V2

**Comment by rezacloner47** [comment]
![image](https://user-images.githubusercontent.com/25543782/44391441-1ba62580-a545-11e8-8478-c4b13ac55751.png)

Pending task was Unmarked.
Done was marked as "Done"
Post was marked as "Postpone"

**Comment by Mohsens22** [comment]
Very interesting bug
