### ISSUE TITLE
Release a Outlook Plugin

### ISSUE THREAD

**Issue by lorisobi** [MahStudio/Denna#95]
Release Outlook Add-In for Denna
-----------------
Please program a version of Denna for Email Clients. Maybe simply in HTML. You have web devs.

PSD:
[DennaConc3.zip](https://github.com/MahStudio/Denna/files/2332672/DennaConc3.zip)

TIFF:
[TIF.zip](https://github.com/MahStudio/Denna/files/2332680/TIF.zip)

**Comment by Mohsens22** [comment]
Hey, thanks for this issue.
I'm currently working on a set of Office plugins that runs in Word, Excel, Access, PP etc.
That project lives here:
https://github.com/MahStudio/DennaForMSOffice
I suggest you to post related stuff there.
